package com.remmylife.gui;

import java.util.Date;

import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.*;

import com.remmylife.diary.*;
import static com.remmylife.head.DiaryType.IMAGE_DIARY;
import static com.remmylife.head.DiaryType.TEXT_DIARY;
import static com.remmylife.head.DiaryType.VIDEO_DIARY;
import static com.remmylife.head.DiaryType.VOICE_DIARY;

import java.sql.SQLException;
import java.text.SimpleDateFormat;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author bestofme
 */
public class DiaryListItem extends javax.swing.JPanel {

    /**
     * Creates new form DiaryListItem
     */
    public DiaryListItem() {
        initComponents();
    }
    
    public DiaryListItem(Diary diary) {
        initComponents();
        
        doMyInitialization(diary);
    }
    
    private void doMyInitialization(Diary diary) {
        
        JLabel titleLabel = jLabel4;
        JLabel dateLabel = jLabel5;
        JLabel typeLabel = jLabel6;
        
        String title = diary.getTitle();
        if (title.length() > 14) {
            title = title.substring(0, 14);
            title += "~";
        }
        titleLabel.setText(title);
        dateLabel.setText(date2string(diary.getDate()));
        
        switch (diary.getType()) {
            case TEXT_DIARY:
                typeLabel.setText("TEXT  ");
                break;
            case IMAGE_DIARY:
                typeLabel.setText("IMAGE");
                break;
            case VOICE_DIARY:
                typeLabel.setText("VOICE");
                break;
            case VIDEO_DIARY:
                typeLabel.setText("VIDEO");
                break;
            default:
                typeLabel.setText("TEXT  ");
        }
        
        id = diary.getId();
        
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
		int clickCount = e.getClickCount();
		if (clickCount == 1) {
                    Diary diary = getDiary(id);
                    if (diary == null)
                        return;
                    switch (diary.getType()) {
                        case TEXT_DIARY: 
                        	TextDiaryDialog dialog = new TextDiaryDialog(null, true, (TextDiary)diary);
                        	dialog.setVisible(true);
                            break;
                        case IMAGE_DIARY:
                            break;
                        case VOICE_DIARY:
                            break;
                        case VIDEO_DIARY:
                            break;
                        default:
                            ;
                    }
		}
            }
        });
    }
    
    private Diary getDiary(int id) { 
        Diary diary = null;
		try {
			diary = UICommonData.Instance().diaryManager.getDiary(id);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} 
        return diary;
    }
    
    public boolean isSelected() {
        return jCheckBox1.isSelected();
    }
    
    public int getid() {
        return id;
    }
    
    public void setMySize() {
        setPreferredSize(new Dimension(220, 44));
    }
    
    private String date2string(Date date) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm");
        return dateFormat.format(date);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Title :");

        jLabel2.setText("Date :");

        jLabel4.setText("jLabel4");

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4))
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
    private int id;
}
