CREATE SCHEMA IF NOT EXISTS `RememberMyLife`;

USE `RememberMyLife`;

CREATE TABLE IF NOT EXISTS `DiaryList` (
	`ID` INT (32) NOT NULL AUTO_INCREMENT,
	`TYPE` ENUM('TEXT_DIARY','IMAGE_DIARY','VOICE_DIARY','VEDIO_DIARY') NOT NULL DEFAULT 'TEXT_DIARY',
	`TITLE` VARCHAR (256) NOT NULL DEFAULT 'New Diary',
	`DATE` VARCHAR (32) NOT NULL DEFAULT '',
	`WEATHER` ENUM('SUNNY','WET','CLOUDY','FOGGY','SNOWY','WINDY') NOT NULL DEFAULT 'SUNNY',
	PRIMARY KEY (`ID`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8;

CREATE TABLE IF NOT EXISTS `TextList` (
	`ID` INT (32) NOT NULL ,
	`TEXT` VARCHAR (4096) ,
	PRIMARY KEY (`ID`),
	CONSTRAINT Main_Text FOREIGN KEY TextList (ID) REFERENCES DiaryList (ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;

CREATE TABLE IF NOT EXISTS `ImageList` (
	`ID` INT (32) NOT NULL ,
	`NOTE` VARCHAR (1028) ,
	`IMAGENAME` VARCHAR(256),
	PRIMARY KEY (`ID`),
	CONSTRAINT Main_Image FOREIGN KEY ImageList (ID) REFERENCES DiaryList (ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;

CREATE TABLE IF NOT EXISTS `VoiceList` (
	`ID` INT (32) NOT NULL ,
	`NOTE` VARCHAR (1028) ,
	`VoiceNAME` VARCHAR(256),
	PRIMARY KEY (`ID`),
	CONSTRAINT Main_Voice FOREIGN KEY VoiceList (ID) REFERENCES DiaryList (ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;

CREATE TABLE IF NOT EXISTS `VideoList` (
	`ID` INT (32) NOT NULL ,
	`NOTE` VARCHAR (1028) ,
	`IMAGENAME` VARCHAR(256),
	PRIMARY KEY (`ID`),
	CONSTRAINT Main_Video FOREIGN KEY ImageList (ID) REFERENCES DiaryList (ID) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE = INNODB DEFAULT CHARSET = utf8 ;
